name: stophone
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# ... (version などの情報は省略)

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies ... (他の依存関係は省略)

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  sensors_plus: ^5.0.1
  flutter_background: ^1.3.0 # 正しいパッケージ名に変更
  cupertino_icons: ^1.0.6
  logger: ^2.4.0
  flutter_local_notifications: ^18.0.1
  flutter_overlay_window: ^0.4.5
# dev_dependencies ... (他の開発用依存関係は省略)

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# ... (残りの部分は省略)
